/**
 * Codegens packages/core/src/generated/elements.ts from
 * datasets/elements/elements.yaml (the single source of truth).
 *
 * @chemistrylab/core stays dependency-free at runtime (no YAML parser, no
 * chemspec) by consuming a plain generated array instead of reading the
 * dataset itself. Run via `pnpm generate:elements`. CI re-runs this and
 * fails the build if the committed output would change.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { parse } from 'yaml';

import { elementDatasetSchema } from '../packages/chemspec/src/element.js';

const repoRoot = path.resolve(import.meta.dirname, '..');
const sourcePath = path.join(repoRoot, 'datasets', 'elements', 'elements.yaml');
const outPath = path.join(repoRoot, 'packages', 'core', 'src', 'generated', 'elements.ts');

const raw = parse(readFileSync(sourcePath, 'utf-8'));
const elements = elementDatasetSchema.parse(raw);

const symbols = elements.map((e) => e.symbol);
const duplicates = symbols.filter((s, i) => symbols.indexOf(s) !== i);
if (duplicates.length > 0) {
  throw new Error(`Duplicate element symbols in elements.yaml: ${duplicates.join(', ')}`);
}

const lines = [
  '// Generated by scripts/generate-elements.ts from datasets/elements/elements.yaml.',
  '// Do not hand-edit — run `pnpm generate:elements` after changing the dataset.',
  '',
  'export interface KnownElement {',
  '  readonly symbol: string;',
  '  readonly atomicNumber: number;',
  '}',
  '',
  'export const KNOWN_ELEMENTS: readonly KnownElement[] = [',
  ...elements.map((e) => `  { symbol: '${e.symbol}', atomicNumber: ${e.atomicNumber} },`),
  '];',
  '',
  'export const KNOWN_ELEMENT_SYMBOLS: ReadonlySet<string> = new Set(',
  '  KNOWN_ELEMENTS.map((e) => e.symbol),',
  ');',
  '',
];

writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf-8');
console.log(`wrote ${path.relative(repoRoot, outPath)} (${elements.length} elements)`);
